# Generated by Django 4.1 on 2022-09-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBicis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BiciVender',
            new_name='VenderBici',
        ),
    ]
